apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: audit-log-verifier
  namespace: audito-maldito
  labels:
    app: audit-log-verifier
spec:
  selector:
    matchLabels:
      app: audit-log-verifier
  template:
    metadata:
      labels:
        app: audit-log-verifier
    spec:
      containers:
      - name: audit-log-verifier
        ports:
          - containerPort: 9172
            name: http
            protocol: TCP      
        image: ghcr.io/angrieralien/audit-log-verifier-exporter:v0.1.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        args:
          -  '--config.file'
          -  '/usr/app/script_exporter.yml'
          -  '--config.shell'
          -  '/bin/bash'
        volumeMounts:
        - name: auditlog
          mountPath: /var/log/audit/audit.log
          readOnly: true
      volumes:
      - name: auditlog
        hostPath:
          path: /var/log/audit/audit.log
