---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: audit-log-verifier-pod-monitor
spec:
  selector:
    matchLabels:
      app: audit-log-verifier
  podMetricsEndpoints:
    - path: probe%3Fname%3Daudit-write-time
      scheme: http
      scrapeTimeout: 5s
      port: http
      params:
        name: audit-write-time 
  namespaceSelector:
    matchNames:
      - audito-maldito
