name: Generate Helm documentation
on:
  workflow_dispatch:
  push:
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow committing and pushing changes to the repo
      pull-requests: write # allow commenting on PRs
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          input: values.yaml
          git-push: true
          git-push-user-name: "github-actions[bot]"
          git-push-user-email: "github-actions[bot]@users.noreply.github.com"
          git-commit-message: "chore: update Helm documentation"
